### PR TITLE
[#61] Fixed bug with second `vault` instance in `run-bats-tests.sh`

### LINKED ISSUE #61: [BUG] `run-bats-tests.sh` doesn't start second vault instance properly
# Description

Sometimes when you run `bats` tests with `make bats` the second instance of `vault` doesn't start.
And because of this, some tests are failing.

# To Reproduce

1. `vault server -dev -dev-root-token-id="root" -dev-listen-address="localhost:8209"`
2. `make bats`

# Expected behavior

The second instance of `vault` starts properly in each `make bats` run

# Environment

- main [0296786](https://github.com/serokell/coffer/commit/0296786c0c70583d2d768d5c17cb909845e18e9f)

### PR DESCRIPTION
**Pull request by DK318**
[//]: # (This is a template of a pull request template.)
[//]: # (You should modify it considering specifics of a particular repository and put it there.)
[//]: # (Comments like this are meta-comments, they shouldn't be present in the final template.)
[//]: # (Comments starting with '

[//]: # (Here you can add a link to the corresponding issue tracker, e. g. https://issues.serokell.io/issue/AD-)
[//]: # (For GitHub/GitLab issues it is better to use just hash symbol or exclamation mark as it is more resistant to repo movements)
[//]: # (In this case please also prefix the link with "Resolves" keyword)
[//]: # (See https://docs.gitlab.com/ee/user/project/issues/managing_issues.html#closing-issues-automatically)
[//]: # (See https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords)
## Related issue(s)
- Fixes #61

#### Related changes (conditional)

- Tests
  - [ ] If I added new functionality, I added tests covering it.
  - [ ] If I fixed a bug, I added a regression test to prevent the bug from
        silently reappearing again.

[//]: # (Add more docs here if you have them in the repository)
- Documentation
  - [x] I checked whether I should update the docs and did so if necessary:
    - [README](../tree/master/README.md)
    - Haddock

[//]: # (Mostly for public repositories)
[//]: # (Recording changes is optional, depends on repository, useful for some libs)
- Public contracts
  - [x] Any modifications of public contracts comply with the [Evolution
  of Public Contracts](https://www.notion.so/serokell/Evolution-of-Public-Contracts-2a3bf7971abe4806a24f63c84e7076c5) policy.
  - [x] I added an entry to the [changelog](../tree/master/CHANGES.md) if my changes are visible to the users
        and
  - [x] provided a migration guide for breaking changes if possible

#### Stylistic guide (mandatory)

[//]: # (Update link to style guide if necesary or remove if it's not present)

- [x] My commits comply with [the policy used in Serokell](https://www.notion.so/serokell/Where-and-how-to-commit-your-work-58f8973a4b3142c8abbd2e6fd5b3a08e).
- [x] My code complies with the [style guide](../tree/master/docs/code-style.md).

### CODE REVIEW

**Comment by dcastro** [comment]
Why did port 8210 not work sometimes? :thinking:

**Comment by DK318** [comment]
Maybe when we start `vault` on port `8209` it uses two ports actually.

If we start manually first instance on port `8201` and try to start the second one on `8202` then we would get next error
````
Error parsing listener configuration.
Error initializing listener of type tcp: listen tcp 127.0.0.1:8202: bind: address already in use
````

**Comment by DK318** [comment]
Yeah, it really listens two neighbor ports. `lsof` prints me this:
````
vault     39914 39926 vault                dk318    8u     IPv4             625209       0t0        TCP localhost:8200 (LISTEN)
vault     39914 39926 vault                dk318    9u     IPv4             625212       0t0        TCP localhost:8201 (LISTEN)
````

**Review by dcastro — APPROVED** [review]

**Comment by MagicRB** [comment]
didnt know vault did that but LGTM

**Review by MagicRB — APPROVED** [review]

**Pull request merged**
